// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Location struct {
	ID        int64
	Name      string
	Lat       float64
	Lon       float64
	CreatedAt time.Time
}
